# Generated by Django 3.1.5 on 2021-01-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210124_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
